@startuml

title __E-COMMERCE's Component Diagram__\n

  component "inventory-web" {
        [inventory-messaging.main]
    component "inventory-messaging.main" {
          [inventory-messaging]
      component "inventory-messaging" {
            [inventory-core.main]
        component "inventory-core.main" {
              [inventory-core]
          component "inventory-core" {
                [e-commerce.main]
            component "e-commerce.main" {
                  [e-commerce]
              component "e-commerce" {
                    [inventory-core.application.main]
                    [inventory-core.adapters.main]
                    [inventory-core.shared.main]
                component "inventory-core.application.main" {
                      [inventory-core.application]
                }


                component "inventory-core.adapters.main" {
                      [inventory-core.adapters]
                  component "inventory-core.adapters" {
                        [inventory-core.adapters.persistence.main]
                    component "inventory-core.adapters.persistence.main" {
                          [inventory-core.adapters.persistence]
                    }


                  }


                }


                component "inventory-core.shared.main" {
                      [inventory-core.shared]
                }


              }


            }


          }


        }


      }


    }


  }


  [inventory-core.adapters.persistence.main] --> [inventory-core.application.main]
  [inventory-core.adapters.persistence.main] --> [inventory-core.shared.main]
  [inventory-core.application.main] --> [inventory-core.shared.main]


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
